[package]
name = "learn-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytemuck = { version = "1.21.0", features = ["derive"] }
env_logger = "0.11.6"
image = { version = "0.25.5", features = ["png", "jpeg"] }
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
