[package]
name = "wgpu-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bytemuck = { version = "1.21.0", features = ["derive"] }
env_logger = "0.11.6"
fastrand = "2.3.0"
log = "0.4.25"
pollster = "0.4.0"
thiserror = "2.0.11"
wgpu = "24.0.1"
winit = "0.30.9"
